name: baby_care_smart_cam
description: A sophisticated BabyCare SmartCam app with Neumorphism & Glassmorphism design
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  percent_indicator: ^4.2.3
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_vlc_player: ^7.4.2
  shared_preferences: ^2.2.2
  ffmpeg_kit_flutter_new_min_gpl: ^2.1.1
  path_provider: ^2.1.5
  tflite_flutter: ^0.10.4
  fftea: ^1.5.0
  audioplayers: ^6.4.0
  mqtt_client: ^10.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/models/
    - assets/icons/
    - assets/images/
    - assets/emotion/
    - assets/audio/

